[package]
name = "my-redis"
version = "0.1.0"
edition = "2024"

[dependencies]
mini-redis = "0.4.1"
tokio = { version = "1", features = ["full"] }
bytes = "1"
futures = "0.3"
rand = "0.10.2"
# ADDED: Required for Streams
tokio-stream = "0.1"      # Provides Stream trait and adapters (take, filter, map)
async-stream = "0.3"      # Provides the stream! macro

[lib]
name = "my_redis"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"
